package com.demo.model;

import com.demo.model.base.BaseExcelDemo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ExcelDemo extends BaseExcelDemo<ExcelDemo> {
	public static final ExcelDemo dao = new ExcelDemo().dao();
}
